version: "3"

tasks:
  zip:
    desc: Zips extension source for upload to Chrome Web Store
    cmds:
      - zip -r extension.zip extension
  firefox-build:
    desc: Signs extension for firefox. Requires APIKEY and APISECRET env variables
    dir: firefox
    cmds:
      - web-ext build --source-dir ../extension
